# Copyright (c) N64-Tools, NetworkFusion and contributers 2023
# See LICENSE file in the project root for full license information.

name: Build windows tools using cygwin

on:
  workflow_call:

jobs:
  build-lib-native:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { arch: x86_64, host: x86_64-w64-mingw32, build: tools} # ,
          # { arch: x86, build: tools}
        ]

    steps:
      - name: Install x-compile system build dependencies
        # if: ${{ matrix.target-platform == 'Windows-x86_64' }}
        run: |
          sudo apt-get install -y mingw-w64
          pacman -S mingw-w64-x86_64-libpng

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1 # Using a shallow checkout. Change to `0` if a full fetch is required.

      - name: Build ${{ matrix.build }}
        run: |
          CC=${{ matrix.host }}-gcc make ${{ matrix.build }}

      - name: "Upload ${{ matrix.build }} executables"
        uses: actions/upload-artifact@v3
        with:
          name: windows-${{ matrix.arch }}-${{ matrix.build }}-cygwin
          path: ${{ github.workspace }}/**/tools/**/*.exe
