# Copyright (c) N64-Tools, NetworkFusion and contributers 2023
# See LICENSE file in the project root for full license information.

name: Build windows tools using mingw

on:
  workflow_call:

jobs:
  build-lib-native:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { arch: x86_64, host: x86_64-w64-mingw32, build: tools} # ,
          # { arch: i686, host: i686-w64-mingw32, build: tools}
        ]

    steps:
      - name: Install x-compile system build dependencies
        run: |
          sudo apt-get install -y mingw-w64 libz-mingw-w64-dev libpng-dev

      - name: x-compile libpng
        run: |
          # mkdir libpng-src
          wget -c https://github.com/glennrp/libpng/archive/refs/tags/v1.6.28.tar.gz -O - | tar -xz # -C ./libpng-src
          # ls -R
          # cd libpng-src/libpng-1.6.28/scripts
          cd libpng-1.6.28/
          ./configure --host=${{ matrix.build }} \
                      --prefix=/usr/${{ matrix.build }} \
                      CPPFLAGS=-I/usr/${{ matrix.build }}/include \
                      LDFLAGS=-L/usr/${{ matrix.build }}/lib
          make -F makefile.gcc
          sudo make install    

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1 # Using a shallow checkout. Change to `0` if a full fetch is required.

      - name: Build ${{ matrix.build }}
        run: |
          CC=${{ matrix.host }}-gcc make ${{ matrix.build }}

      - name: "Upload ${{ matrix.build }} executables"
        uses: actions/upload-artifact@v3
        with:
          name: windows-${{ matrix.arch }}-${{ matrix.build }}-mingw
          path: ${{ github.workspace }}/**/tools/**/*.exe
