# Copyright (c) libdragon and contributers 2023
# See LICENSE file in the project root for full license information.

on: workflow_call

jobs:
  Build-library-native:
    uses: ./.github/workflows/build-lib-native.yml

  Build-Tools-Windows-msys2:
    uses: ./.github/workflows/build-tools-windows-msys2.yml

  Generate-Windows-Tools-Release:
    runs-on: ubuntu-latest
    needs: [Build-Tools-Windows-msys2, Build-library-native]
    steps:
      - name: Download x86_64 Windows artifact
        id: download-x86_64-windows-artifact
        uses: actions/download-artifact@v3
        with:
          name: "windows-x86_64-tools"
          path: ${{ runner.temp }}/windows-artifact-download/windows-x86_64-tools

      - name: Download i686 Windows artifact
        id: download-i686-windows-artifact
        uses: actions/download-artifact@v3
        with:
          name: "windows-i686-tools"
          path: ${{ runner.temp }}/windows-artifact-download/windows-i686-tools

      - name: Download lib artifact
        id: download-libdragon-artifact
        uses: actions/download-artifact@v3
        with:
          name: "libdragon-lib"
          path: ${{ runner.temp }}/libdragon-lib

      # Compress and move the folders ready for upload.
      - name: Compress and move windows artifacts
        run: |
          cd ${{ steps.download-x86_64-windows-artifact.outputs.download-path }}
          zip -r -q ${{ runner.temp }}/libdragon-tools-win_x86_64.zip *

          cd ${{ steps.download-i686-windows-artifact.outputs.download-path }}
          zip -r -q ${{ runner.temp }}/libdragon-tools-win_i686.zip *

          cd ${{ steps.download-libdragon-artifact.outputs.download-path }}
          zip -r -q ${{ runner.temp }}/libdragon-library.zip *
        continue-on-error: true

      - name: Generate Pre-Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          name: "${{ github.ref_name }}-windows-tools-latest"
          tag_name: "${{ github.ref_name }}-windows-tools-latest"
          files: |
            ${{ runner.temp }}/**/*.zip
